name: bmi
description: "BMI tracker app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  easy_localization: ^3.0.2
  flutter_screenutil: ^5.8.2
  json_annotation: ^4.8.1
  pull_to_refresh: ^2.0.0
  dot_navigation_bar: ^1.0.2
  pretty_gauge: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - res/assets/
    - res/localization/